kind: Service 
apiVersion: v1 
metadata: 
  name: angular-service  
spec: 
  selector: 
    app: angular-devops 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 31000 
  type: NodePort 
