kind: Service 
apiVersion: v1 
metadata: 
  name: angular-service  
spec: 
  selector: 
    app: angular-devops 
  ports: 
  - protocol: TCP 
    nodePort: 30300
    port: 4444
    targetPort: 4444
  type: NodePort 
